unit Pas2JS.Consts;

interface

const
  APPLICATION_TYPE = 'Pas2JS';

  PAS2JS_ABSOLUTE_FILE_NAME_MAP_FILE = 'Pas2JS_AbsoluteFileName';
  PAS2JS_APPLICATION_ICON = 'Pas2JS_Icon';
  PAS2JS_APPLICATION_TITLE = 'Pas2JS_ApplicationName';
  PAS2JS_CHECK_INTEGER_OVERFLOW = 'Pas2JS_IntegerOverflow';
  PAS2JS_CHECK_OBJECT_TYPE_CAST = 'Pas2JS_CheckObjects';
  PAS2JS_ENUMERATOR_AS_NUMBER = 'Pas2JS_EnumNumber';
  PAS2JS_INCLUDE_SOURCE_MAP_FILE = 'Pas2JS_IncludeSource';
  PAS2JS_GENERATE_MAP_FILE = 'Pas2JS_MapFile';
  PAS2JS_GENERATE_SINGLE_FILE = 'Pas2JS_SingleFile';
  PAS2JS_MAP_FILE_PROTECTION = 'Pas2JS_Map_File_Protection';
  PAS2JS_MODULES = 'Pas2JS_Modules';
  PAS2JS_RANGE_CHECK_ERROR = 'Pas2JS_RangeCheck';
  PAS2JS_RELATIVE_SOURCE_FOLDER = 'Pas2JS_Relative_Folder';
  PAS2JS_REMOVE_NOT_USED_DECLARATIONS = 'Pas2JS_RemoveNotUsedDeclaration';
  PAS2JS_REMOVE_NOT_USED_PRIVATES = 'Pas2JS_RemoveNotUsedPrivate';
  PAS2JS_RESOURCE_DIRECTORY_PATH = 'Pas2JS_DirectoryResource';
  PAS2JS_SEARCH_PATH = 'Pas2JS_Search';
  PAS2JS_SOURCE_ROOT_FOLDER = 'Pas2JS_SourceRoot';
  PAS2JS_USE_CORBA_INTERFACE = 'Pas2JS_UseCORBAInterface';

implementation

end.
